fix(crash): Update parry2d to 0.13.7 (use rapier fork) for crash fix in QBVH (#960)
I've been frequently hitting a crash / bug in parry2d QBVH involving
incremental update. Sometimes it crashes, sometimes is a framerate death
spiral / fully locks up.

```
thread 'main' panicked at /Users/max/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parry2d-0.13.6/src/partitioning/qbvh/update.rs:367:54:
attempt to add with overflow
```

Appears to be been fixed at
https://github.com/dimforge/parry/commit/7df2728afc8eff3c4ba7256b3344968481524b37
in parry2d 0.13.7. Updated rapier to use a fork with parry2d update as
not updated in rapier yet.